build/frontend/action.yaml
deploy/frontend/action.yaml
packages/makefile/action.yaml
packages/rancher/action.yaml

- add input working directory for monorepo
- update sequence get helm history

ci: add input working directory for monorepo

---

build/frontend/action.yaml
deploy/frontend/action.yaml
packages/pnpm/action.yaml
packages/yarn/action.yaml

fix: setup yarn

---

packages/yarn/action.yaml

fix: yarn action

---

build/frontend/action.yaml
packages/buildx/action.yaml
packages/pnpm/action.yaml
packages/yarn/action.yaml

- feat: add input pnpm version on build

feat: add input pnpm version on build

---

packages/pnpm/action.yaml
packages/yarn/action.yaml

fix: nextjs cache path

---

build/frontend/action.yaml
packages/makefile/action.yaml

- feat(frontend): implement config upload cdn assets after build

feat(frontend): implement config upload cdn assets after build

---

build/frontend/action.yaml
destroy/action.yaml
packages/buildx/action.yaml
packages/cdn/action.yaml
packages/makefile/action.yaml
packages/pnpm/action.yaml
packages/yarn/action.yaml

- ci: configurable make install / config / build / package on build actions
- ci: configurable cache for disable on benchmark clean build
- ci: configurable make prune-all for destroy actions

ci: configurable makefile on build action

---

build/frontend/action.yaml
packages/makefile/action.yaml

- feat(build): frontend add build time duration output

feat(build): frontend add build time duration output

---

build/backend/action.yaml
deploy/backend/action.yaml

added deployment status so you can check it from JIRA
only triggered during **deploy** action

feat(be): added deployment status during deploy

---

unit_test/backend/README.md
unit_test/backend/action.yaml

added unit test composite action

feat: added unit test composite

---

build/backend/action.yaml

Update setup go v3 to v4
Context: [slack chat](https://kitabisa.slack.com/archives/C9UE1EL2K/p1679882400922239)

feat(be): update setup-go v3 to v4

---

build/frontend/action.yaml
destroy/action.yaml
packages/cdn/action.yaml
packages/makefile/action.yaml
tools/frontend/lighthouse/action.yaml
tools/frontend/nextjs-bundle-analysis/action.yaml

- setup cdn compatibility for monorepo and multiple env
- add fe tools for audit lighthouse
- add fe tools for audit nextjs bundle analysis

feat: setup cdn compatibility for monorepo

---

coverage/backend/action.yaml
coverage/backend/readme.MD
unit_test/backend/action.yaml

Added action to generate badge which can be used in your own readme.MD
Location of the badge will be in .github/badges/code-coverage.svg

feat: added action composite to generate badge

---

deploy/backend/action.yaml
packages/makefile/action.yaml

default value boolean doesn't work so need to be fixed

fix: setup helmfiles parameter in deploy backend

---

coverage/backend/action.yaml
unit_test/backend/action.yaml

feat: implement proper numeric comparison on unit test

---

backend/tools/coverage/action.yaml

coverage-masters.txt ga kecommit karena by default dia baca path `service`

fix: added working directory during commit coverage master file

---

sdet/automation-test/action.yaml
sdet/deploy/README.md
sdet/deploy/action.yaml

- update report history sdet
- enable steps for all platform

chore: update report history sdet QE-1042

---

backend/unit_test/action.yaml

added changes to cover only new code instead all code coverage

ci: cover only new code

---

.github/workflows/release-please-main.yml

Changelog: fix
forget to set id on step release please

fix(workflow): forget to set id on step release please

---

.github/workflows/pre-commit.yaml
.pre-commit-config.yaml

Changelog: fix
disable pre-commit check for release-please

fix(workflow): disable pre-commit check for release-please

---

.github/workflows/pre-commit.yaml

Changelog: feature
Add type for pull request

feat(workflow): Add type for pull request

---

backend/destroy/action.yaml

feat: fix release

---

backend/deploy/action.yaml

feat: fix deploy be to reopen

---

infra/tools/taskfile/Taskfile.yaml

fix: fix taskfile mysql

---

infra/deploy/terragrunt/action.yaml

fix warning inputs on terragrunt

---

infra/deploy/terragrunt/action.yaml

fix: warning inputs on terragrunt

---

infra/tools/taskfile/action.yaml

fix: warning inputs on taskfile

---

backend/build/action.yaml
backend/cache/action.yaml
backend/coverage/action.yaml
backend/unit_test/action.yaml

added suffix cache so cache wont be rolled together causing massive size cache, slowing the CI process

feat: added suffix cache

---

infra/tools/artifact-registry/action.yaml

fix: composite artifact registry gke creds set to false

---

frontend/tools/pnpm/action.yaml
frontend/tools/yarn/action.yaml

fix: fix frontend cache

---

sdet/trigger-automation-test-when-deploy/action.yaml

fix: description action

---

sdet/automation-test/action.yaml

- add new variable for support kitafund project using dotenvx

ci: update env for kitafund

---

sdet/automation-test/action.yaml

- add new variable for support env mobile using dotenvx

ci: update env variable for support mobile

---

sdet/automation-test/action.yaml

fix: remove unused variable key

---

sdet/trigger-automation-test-when-deploy/action.yaml

- handle branch gh when trigger automation test

fix: handle branch gh when trigger

---

sdet/trigger-automation-test-when-deploy/action.yaml

- handle command base on merge to master

fix: command base on merge to master

---

sdet/trigger-automation-test-when-deploy/action.yaml

- handle could not create workflow dispatch event

fix: dispatch event pr

---

infra/unit_test/helmfiles/action.yaml

feat: add auth dockerhub oci

---

sdet/automation-test/action.yaml

fix: handle env variables

---

README.md

feat: change readme

---

.github/workflows/release-please-main.yaml

fix: rollback github token

---

infra/tools/makefile/action.yaml

feat: add github source env

---

infra/tools/makefile/action.yaml

feat: add git source make source

---

infra/tools/makefile/action.yaml

feat: change env values

---

infra/tools/rancher/action.yaml

feat: force run rancher ns mover

---

backend/deploy/action.yaml
infra/tools/ghcr-credential/README.md
infra/tools/ghcr-credential/action.yaml

feat: add ghcr credential

---

backend/deploy/action.yaml
infra/deploy/helmfiles/action.yaml

add composite module gchr to deploy/ and infra/

---

backend/deploy/action.yaml
infra/deploy/helmfiles/action.yaml

chore: retrigger release please add ghcr

---

backend/deploy/action.yaml
infra/deploy/helmfiles/action.yaml

feat: add missing parameter and remove unused

---

sdet/automation-test/README.md
sdet/automation-test/action.yaml

- remove unused code and update readme

fix: remove unused code

---

frontend/deploy/action.yaml

feat: update frontend comment actions

---

frontend/deploy/action.yaml

fix: fix comment action on PR

---

sdet/automation-test/README.md
sdet/automation-test/action.yaml

ci: add cache steps for summary

---

sdet/automation-test/README.md
sdet/automation-test/action.yaml
sdet/deploy/action.yaml
sdet/tools/dispatch/action.yaml

- adjust for automation test mobile
- remove inputs github_run_number

chore: automation test mobile SDET-1267

---

sdet/automation-test/action.yaml

- restore cache only if run attempt > 1

fix: restore cache if rerun SDET-1267

---

frontend/deploy/action.yaml

feat: update preview-url chart v2

---

backend/unit_test/README.md
backend/unit_test/action.yaml

with non strict false, allow to go
non strict true
gh comment
strict check true
strict check false

feat: added strict and non strict test

---

backend/build/action.yaml
backend/cache/action.yaml
backend/coverage/action.yaml
backend/unit_test/action.yaml

added date on cache for uniqueness

ci: added date on cache

---

backend/build/action.yaml
backend/cache/action.yaml
backend/coverage/action.yaml
backend/unit_test/action.yaml

Changed cache format on the composite backend build, test, coverage and cache workflow

feat: updated ci cache format

---

frontend/deploy/action.yaml

feat: trigger release tag for frontend update

---

frontend/deploy/action.yaml

fix: deployment frontend

---

infra/build/dockerfile/action.yaml

feat: add composite dockerfiles

---

infra/build/dockerfile/action.yaml

fix: trim-trailing-whitespace

---

frontend/deploy/action.yaml

fix: conditional comment preview

---

infra/build/dockerfile/action.yaml

feat: specifiec cache dst

---

infra/build/dockerfile/action.yaml

feat: update convention label oci

---

sdet/automation-test/action.yaml

- update field repository for comment pr release step

fix: update field repo SDET-1488

---

infra/build/dockerfile/action.yaml

fix: whitespace

---

infra/build/dockerfile/action.yaml

This PR for reordering input on build docker

feat: reorder input

---

infra/build/dockerfile/action.yaml

This PR uses for auto image version updater when dependabot changes

feat: sync image updater

---

infra/build/dockerfile/action.yaml

Change github user to dependabot

feat: change to dependabot user

---

infra/build/dockerfile/action.yaml

fix: retrigger to fix condition

---

infra/build/dockerfile/action.yaml

fix: condition author dependabot not working

---

infra/build/dockerfile/action.yaml

add author input for check if dependabot user should create new pr and bypass build

feat: add author input

---

sdet/automation-test/README.md
sdet/automation-test/action.yaml

- add `insert_testiny` to call function for sending a test result to Testiny
- add `custom_command_post_run` to handle a needed custom command post the run test

chore: add send result to testiny and custom command post run

---

sdet/post-pr/action.yaml
sdet/pr-metrics/action.yaml

fix: ignore ssl cert and load dotenvx

---

infra/build/dockerfile/action.yaml

feat: move checkout in workflow

---

backend/deploy/action.yaml
infra/tools/dockerhub-credential/action.yaml

feat(infra): ID-888 add dockerhub auth

---

frontend/deploy/action.yaml

feat(frontend): add dockerhub auth
